### ISSUE TITLE
Error installing with pip install oasys1 --upgrade

### ISSUE THREAD

**Issue by dsdale24** [oasys-kit/OASYS1#18]
Good morning,

I'm attempting a fresh install on Windows 10. It looks like there may be an incompatibility with the Conda's current python version 3.12 and numpy < 1.26. OASYS is specifying numpy<1.23:

```
> pip install oasys1 --upgrade
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000140400A4410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/oasys1/
Collecting oasys1
  Using cached OASYS1-1.2.146.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in c:\users\dd55\appdata\local\anaconda3\lib\site-packages (from oasys1) (75.6.0)
Requirement already satisfied: requests in c:\users\dd55\appdata\local\anaconda3\lib\site-packages (from oasys1) (2.32.3)
Collecting numpy<1.23,>=1.21 (from oasys1)
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\dd55\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\dd55\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dd55\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\dd55\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\dd55\AppData\Local\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\dd55\AppData\Local\Temp\pip-build-env-8usqs_rl\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\dd55\AppData\Local\Temp\pip-build-env-8usqs_rl\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\dd55\AppData\Local\Temp\pip-build-env-8usqs_rl\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by lucarebuffi** [comment]
Please follow installation instructions in:

https://github.com/oasys-kit/oasys-installation-scripts/wiki/Install-Oasys-in-Windows-10%E2%80%9011

There is a specific version of Miniconda that is supported (python 3.8). We are working on a new release with python 3.11 but it is not ready, yet.

We do not offer assistance on non-standard installation of OASYS.
